### ISSUE TITLE
Use Supplier for TagFactory instead of requiring no-args constructor

### ISSUE THREAD

**Issue by Marcono1234** [Querz/NBT#10]
It might be better to change the method `TagFactory.registerCustomTag(int, Class<? extends Tag>)` to `TagFactory.registerCustomTag(int, Supplier<? extends Tag<?>>)`.

This forces the user to either have a no-args constructor and pass it as supplier, or to have a factory method. Either way prevents the case where the user forgot to add a no-args constructor.

**Comment by Querz** [comment]
Good point, see #16
