### ISSUE TITLE
Reverse nesting depth

### ISSUE THREAD

**Issue by Marcono1234** [Querz/NBT#25]
This is only an idea, might not be worth to implement it.

It might be good to reverse the nesting depth. Currently it is incremented until it reaches `MAX_DEPTH`, however it might be more user friendly if instead you provide the max depth (or the default is used) and it is then decremented instead. This makes it easier for the user to specify the maximum nesting depth instead of having to calculate it based on the `MAX_DEPTH`.

**Comment by Marcono1234** [comment]
Or maybe the nesting depth could still be incremented (like it is currently the case), but the maximum depth should be an additional parameter. Though that might make it more complicated.

**Comment by Querz** [comment]
When using the NBT protocol, it should be clear that the maximum depth must not exceed 512, see https://minecraft.gamepedia.com/NBT_format.

The `#serializeValue(DataOutputStream, int)`, `#deserializeValue(DataInputStream, int)`, `#toString(int)`, `#toTagString(int)`, `#valueToString(int)` and `#valueToTagString(int)` methods already provide a way to influence the depth of the structure, up to `MAX_DEPTH`.

**Comment by Marcono1234** [comment]
It looks like this part of the wiki is an observation and only a limit imposed by Minecraft now.

Neither https://wiki.vg/NBT#Specification nor the original [specification](https://web.archive.org/web/20110723210920/http://www.minecraft.net/docs/NBT.txt) mention it.

Additionally since this library already supports custom types, it might be useful to allow custom nesting depths as well.

**Comment by Querz** [comment]
if that's the case, nothing speaks against a customisable depth. I'd prefer to invert it though, so you start with the highest number and approach 0, because this won't require an additional "limit" value.
