### ISSUE TITLE
Remove Tag.getEmptyValue()

### ISSUE THREAD

**Issue by Marcono1234** [Querz/NBT#28]
In my opinion it might be good to replace `Tag.getEmptyValue()` with public constants (or factories for `ListTag` and `CompoundTag`). Additionally the ability to provide `null` when constructing tags which results in the default value being used might be error-prone. Instead the argument should be non-null and the no-arg constructors could pass the default value to it.
If it is unknown whether a value is `null`, maybe constructors with an `Optional` parameter could be added in case it is needed.

The method `Tag.getEmptyValue()` encourages bad performing code, see 
https://github.com/Querz/NBT/blob/74e37d4986a27b66113abd2c59a9d78e6c9a4900/src/main/java/net/querz/nbt/CompoundTag.java#L124-L172

**Comment by Querz** [comment]
See #27 
I also made the `Tag()` constructor protected so each `Tag` implementation must specify their own no-args constructor and set their default value. If the only action inside this no-args constructor is a call to `Tag()`, the value will be `null`. This might be needed for custom tags (e.g. `ObjectTag`).

**Comment by Marcono1234** [comment]
Maybe it would be better to have a `validateValue` method which by default prevents `null` and then have `ObjectTag` override it.

Also there are currently multiple problems with `ObjectTag`:
- `new ObjectTag().setValue(null)` throws NPE
- `ObjectTag#hashCode` throws NPE for null values
-  `ObjectTag#clone` should not catch NPE, instead null check should be done
- `ObjectTag#compareTo` a other `null` value equal to this, even if this value might not be `null`

**Comment by Querz** [comment]
I fixed these so far. `ObjectTag#compareTo` calls a `compareTo` method if the values of both `ObjectTag`s implement `Comparable`. If not, it checks if both values are the same. It returns `1` if the value of this `ObjectTag` is `null` but the value of the other isn't and `-1` if the value of the other `ObjectTag` is `null` but the value of this `ObjectTag` isn't.

Currently i simply return `0` if none of the above conditions match.
