### ISSUE TITLE
Cannot cast net.querz.nbt.ByteArrayTag to net.querz.nbt.IntArrayTag

### ISSUE THREAD

**Issue by antonilol** [Querz/NBT#38]
When i executed this:
`MCAFile mcaFile = MCAUtil.readMCAFile("r.0.0.mca");`
this error occurs:
`java.lang.ClassCastException: Cannot cast net.querz.nbt.ByteArrayTag to net.querz.nbt.IntArrayTag`

The file r.0.0.mca exists

Anyone help me

**Comment by Tacodude7729** [comment]
Also getting this issue.

**Comment by amooose** [comment]
This is due to Chunk.java line 65.
Simply comment out `this.biomes = level.getIntArray("Biomes");`
It'll work, at the expense of not having biome information, I haven't looked into it further.

**Comment by Querz** [comment]
This is due to Minecraft 1.13+ using an IntArrayTag to store biome ids, while older versions still use a ByteArrayTag.

**Comment by Querz** [comment]
The MCA library does currently not support Minecraft versions below 1.13. It is unlikely, that I will make it backwards compatible.
