### ISSUE TITLE
Doesn't work with >= 1.15.1

### ISSUE THREAD

**Issue by FarmitzDugan** [Querz/NBT#39]
Biome data was changed and now you can get biome data based on (x,z) see my super simple example and code comments:
```
package com.company;

import net.querz.nbt.mca.MCAFile;
import net.querz.nbt.mca.MCAUtil;
import java.io.IOException;

public class Main {
    public static void main(String[] args) throws IOException {
        int biome;
        MCAFile mcaFile1 = MCAUtil.readMCAFile("FD-000010/input/region/r.0.0.mca"); // 1.14.4 file
        biome = mcaFile1.getBiomeAt(72,26);
        System.out.println(biome); // should output 17 and does
        MCAFile mcaFile2 = MCAUtil.readMCAFile("FD-000011/input/region/r.0.0.mca"); // 1.15.1 file
        biome = mcaFile2.getBiomeAt(72,26);
        System.out.println(biome); //should output 3 but outputs -1
        MCAFile mcaFile3 = MCAUtil.readMCAFile("FD-000012/input/region/r.0.0.mca"); // 1.15.2 file
        biome = mcaFile3.getBiomeAt(28,53);
        System.out.println(biome); //should output 162 but outputs -1
    }
}
```
[Get Biomes 1.15.1.zip](https://github.com/Querz/NBT/files/4110265/Get.Biomes.1.15.1.zip)

**Comment by Querz** [comment]
Fixed this in the latest release (5.2).
They added support for vertical biomes in 1.15. Biomes are now stored in a 1024 long int array containing the biome of a 4x4x4 section of the chunk. This reduces the resolution of the biomes.

The F3-Screen in the game also doesn't always show the actual biome saved in the region files. It somehow blurs the edges of biomes. I explain this [here](https://github.com/Querz/mcaselector/issues/93#issuecomment-616460484) using MCA Selector.
