### ISSUE TITLE
Distribute via Maven?

### ISSUE THREAD

**Issue by Xerosigma** [Querz/NBT#43]
Would love to pull this down through gradle.

**Comment by Querz** [comment]
It is currently published on Jitpack. You can use it with Gradle like this:

```
repositories {
	...
	maven { url 'https://jitpack.io/' }
}
```
And then add it as a dependency as usual:
```
dependencies {
	...
	compile 'com.github.Querz:NBT:5.2'
}
```

I added this information to the Readme.
