### ISSUE TITLE
Please merge the little-endian-io-SNAPSHOT branch over the recommended public branch(es)

### ISSUE THREAD

**Issue by mjevans** [Querz/NBT#54]
There's at least one fix in your experimental branch that was the difference between a corrupted set of world files and working world files.

https://github.com/Querz/mcaselector/blob/master/build.gradle

Your other (thank you it works well!) program is able to trim chunks without eating my world files and in this project pulls in: 	implementation 'com.github.Querz:NBT:little-endian-io-SNAPSHOT'

I _suspect_ that it's a combination of the logical and for the loadflags (part of commit ef9433bb519fd8edbca5afa9490afd184e0b2dba ) and also the next patch after that made everything reference the static class variable (rather than a mix of instance and static class variables), but quite a bit ( 90646abb469c2c96e16f36fdca5fcb966b2f758a ) which fixed the chunk math ( return biomeY * 16 + biomeZ * 4 + biomeX );  Though that would make more sense to me as a series of bit-shifts ( return Y << 4 + Z << 2 + X << 0 ).

PS: I figured out this is what I needed to pull based on looking at the build file for your other project, since I wanted to know what I was doing wrong in trying to write a tiny java program to use the same base library to fix some shuffled mod-biomes for a mod-pack that added new biomes during updates.

**Comment by Querz** [comment]
Merged and created new release [6.0](https://github.com/Querz/NBT/releases/tag/6.0).
